#!/usr/bin/env bash

set -e

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
DOTBOT_CONFIG="install.yaml"


# Initialize the DotBot submodule required to install the dot files.
# All other submodules should be configured in DOTBOT_CONFIG file.
cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"


"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${DOTBOT_CONFIG}" "${@}"


# Clean up
unset BASEDIR DOTBOT_DIR DOTBOT_BIN DOTBOT_CONFIG
